export const interview = [
  {
    id: '1',
    title: 'InterView 1 ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    time: ' 5 min ',
    image: 'https://oztilingsolutions.com.au/test/icon/icon1.png',
    color: ['#FF6510', '#FFBE94'],
    colorOne: '#F27A25',
    colorTwo: '#FFC79F',
  },
  {
    id: '2',
    title: 'InterView 2 ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    time: ' 10 min ',
    image: 'https://oztilingsolutions.com.au/test/icon/icon2.png',
    color: "'#FF6510', '#FFBE94'",
    colorOne: '#484ED7',
    colorTwo: '#A6BDFE',
  },
  {
    id: '3',
    title: 'InterView 1 ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    time: ' 5 min ',
    image: 'https://oztilingsolutions.com.au/test/icon/icon3.png',
    color: "'#FF6510', '#FFBE94'",
    colorOne: '#56BE86',
    colorTwo: '#AFE5CA',
  },
  {
    id: '4',
    title: 'InterView 1 ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    time: ' 5 min ',
    image: 'https://oztilingsolutions.com.au/test/icon/icon4.png',
    color: "'#FF6510', '#FFBE94'",
    colorOne: '#DE58D8',
    colorTwo: '#EE9FE6',
  },
  // {
  //   id: 2,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 10 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon2.png',
  //   color: "['#3B3DD3', '#94B4FF']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
  // {
  //   id: 3,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 12 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon3.png',
  //   color: "['#00B775', '#8EE5C4']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
  // {
  //   id: 4,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 13 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon4.png',
  //   color: "['#F637D5', '#FF90E5']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
  // {
  //   id: 5,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 5 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon1.png',
  //   color: "['#FF6510', '#FFBE94']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
  // {
  //   id: 6,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 10 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon2.png',
  //   color: "['#3B3DD3', '#94B4FF']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
  // {
  //   id: 7,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 12 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon3.png',
  //   color: "['#00B775', '#8EE5C4']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
  // {
  //   id: 8,
  //   title: 'InterView 1 ',
  //   details: 'Lorem Ipsum Doller sit amet Recommended',
  //   time: ' 13 min ',
  //   image: 'https://oztilingsolutions.com.au/test/icon/icon4.png',
  //   color: "['#F637D5', '#FF90E5']",
  //   colorOne: '"#FF6510"',
  //   colorTwo: '"#FFBE94"',
  // },
];

export const category = [
  {
    id: '1',
    title: 'InterView 1 ',
    colorOne: '#F27A25',
    colorTwo: '#FFC79F',
  },
  {
    id: '2',
    title: 'InterView 2 ',
    colorOne: '#484ED7',
    colorTwo: '#A6BDFE',
  },
  {
    id: '3',
    title: 'InterView 1 ',

    colorOne: '#56BE86',
    colorTwo: '#AFE5CA',
  },
  {
    id: '4',
    title: 'InterView 1 ',
    colorOne: '#DE58D8',
    colorTwo: '#EE9FE6',
  },
];

export const LineChartData = [
  {
    title: 'Expression2',
    circleColor: '#F17720',
    lineColor: '#F17720',
    areaColor: 'rgba(251, 124, 0, 0.52) -66.51%',
    markerColor: '#F17720',
  },
  {
    title: 'Expression3',
    circleColor: '#4449D5',
    lineColor: '#4449D5',
    areaColor: '#758EEC',
    markerColor: '#4449D5',
  },
  {
    title: 'Expression4',
    circleColor: '#24CCD9',
    lineColor: '#24CCD9',
    areaColor: '#1AD4DD',
    markerColor: '#24CCD9',
  },
  {
    title: 'Expression5',
    circleColor: '#DC51D7',
    lineColor: '#DC51D7',
    areaColor: '#ED9DE5',
    markerColor: '#DC51D7',
  },
];
