export const dataAll = [
  {
    id: '4',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image1.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFC3AF',
  },
  {
    id: '5',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '6',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '7',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image1.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFC3AF',
  },
  {
    id: '8',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '9',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '10',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image1.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFC3AF',
  },
  {
    id: '11',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '12',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
];
export const dataMain = [
  {
    id: '4',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image1.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFC3AF',
  },
  {
    id: '5',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '6',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
];
export const dataWeb = [
  {
    id: '7',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image1.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFC3AF',
  },
  {
    id: '8',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '9',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
];
export const dataOther = [
  {
    id: '10',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image1.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFC3AF',
  },
  {
    id: '11',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
  {
    id: '12',
    title: 'How To Work ? ',
    details: 'Lorem Ipsum Doller sit amet Recommended',
    image: 'https://oztilingsolutions.com.au/test/article/image2.png',
    color: "['#FF6510', '#FFBE94']",
    bgColor: '#FFD3D6',
  },
];
